Add CASTEP package
EPCCed/spack-archer2 pull request #1
Opened 2024-08-07 15:50 UTC by NMannall

Add package for installing CASTEP. The package requires the tar.gz file of the CASTEP source code to exist in the current directory (or have been added to a mirror created by the user before the installation).

2024-08-07 16:22 UTC, welucas2 requested changes
Thanks Nathan, just one thing below.

2024-08-07 16:22 UTC, welucas2 commented on var/spack/repos/archer2/packages/castep/package.py
> +    license("UNKNOWN")
Non-free software packages with their own non-SPDX licences seem to simply leave out the `license()` directive. Could these lines be deleted? Otherwise I think this looks good!

2024-08-08 09:38 UTC, NMannall commented on var/spack/repos/archer2/packages/castep/package.py
> +    license("UNKNOWN")
The next commit resolves this

2024-08-12 11:32 UTC, welucas2 commented
Thanks, merging in now.

2024-08-12 11:32 UTC, merged